
name: Ping Deploy

on:
  push:
    branches: [ v2 ]
  pull_request:
    branches: [ v2 ]

jobs:
  deploy:
    name: Ping deploy
    runs-on: self-hosted
    steps:
    - name: Git Checkout Latest
      uses: actions/checkout@v2
      
    - name: deploy
      run: yarn install
      run: yarn run vue-cli-service build