
name: Ping Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    name: Ping deploy
    runs-on: self-hosted
    steps:
    - name: Git Checkout Latest
      uses: actions/checkout@v2
      
    - name: Install
      run: yarn install

    - name: Build
      run: yarn run vue-cli-service build

    - name: Deploy
      run: cp -rf ./dist/* /var/www/html/